version: '3.8'

services:
  db:
    image: postgres:12
    container_name: hotels_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: hotels_redis

  hotels:
    image: puk #костыль-джан
    build:
      context: .
    container_name: hotels_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/hotels/docker/app.sh"]
    ports:
      -  7777:8000

  celery:
    build:
      context: .
    container_name: hotels_celery
    command: ["/hotels/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: hotels_flower
    command: [ "/hotels/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      -  3000:3000

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:
